name: CI/CD Docker FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозиторий
      uses: actions/checkout@v3

    - name: Установить Docker
      uses: docker/setup-buildx-action@v2

    - name: Логин в Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Сборка и пуш Docker образа
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-recommender:latest

    - name: (опционально) Деплой на сервер
      run: echo "Deploy logic here — например, SSH на VPS"
